services:
  - type: web
    name: cyber-threat-map-fullstack
    env: node
    buildCommand: pnpm install --frozen-lockfile && pnpm run build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
